version: '3'
services:
  db:
    hostname: db
    image: mysql:8.0.27
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: beerProjectDevelop
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    restart: always
  api:
   # image: martin056/beer-api:1.0
    build: .
    hostname: beerApp
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
      WAIT_BEFORE_HOSTS: 15
    links:
      - db:db
    restart: always