version: '3'
services:
  db:
    hostname: db
    image: mysql:8.0.27
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    restart: always
  api:
    #  image: martin056/beer-api:1.1
    build: .
    hostname: beerApp
    ports:
      - ${API_PORT}:8081
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_SCHEMA: ${DATABASE_SCHEMA}
    restart: always