pipeline {
    agent any

    tools{
        maven "M3"
    }


    stages {
        stage('Build') {
            steps {
                echo 'Compiling..'
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                 sh 'mvn test'
            }
        }
        stage('Packaging') {
            steps {
                echo 'Packaging....'
                  sh 'mvn package'
            }
        }
    }
}