pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('Compiling') {
            steps {
                dir('BeerProject') {
                    echo 'Compiling..'
                    sh 'mvn clean compile'
                }

            }
        }

//         stage('Test') {
//             steps {
//                 dir('BeerProject') {
//                     echo 'Testing..'
//                     sh 'mvn test'
//                 }
//             }
//         }

        stage('Sonarqube analyze') {
            steps {
                dir('BeerProject') {
                    withCredentials([
                        string(credentialsId: 'jenkins_token', variable: 'JENKINS_TOKEN')
                    ]){
                        echo MAVEN_SETTINGS
                        echo 'run analyze..'
                        withSonarQubeEnv('SonarQube'){
                            sh 'mvn sonar:sonar -Dsonar.login=Jenkins -Dsonar.password=JENKINS_TOKEN'
                        }
                    }
                }
            }
        }

        stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Packaging') {
            steps {
                dir('BeerProject') {
                    echo 'Packaging....'
                    sh 'mvn package'
                }
            }
        }
    }
}