pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('verify tooling') {
            steps {
                 sh '''
                 docker-compose -v
                 '''
            }
        }

        stage('Compiling') {
            steps {
                dir('BeerProject') {
                    echo 'Compiling..'
                    sh 'mvn clean compile'
                }

            }
        }

        stage('Test') {
            steps {
                dir('BeerProject') {
                    echo 'Testing..'
                    sh 'mvn test'
                }
            }
        }

        stage('Sonarqube analyze') {
            steps {
                dir('BeerProject') {
                        echo 'run analyze..'
                        withSonarQubeEnv('SonarQube'){
                            sh 'mvn clean install sonar:sonar'
                        }

                }
            }
        }

        stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Packaging') {
            steps {
                dir('BeerProject') {
                    echo 'Packaging....'
                    sh 'mvn package -Dmaven.test.skip'
                }
            }
        }
    }
}