spring:
  profiles:
    active: production
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 6MB
server:
  port: 8085

logging:
  config: classpath:logback/logback.xml

image:
  path: src/main/resources/images/.
  requirements:
    standard-type: image/jpeg, image/jpg, image/png, image/bpm
    max-file-size: 5242880