spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 6MB
server:
  servlet:
    context-path: "/api/v1/"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  config: classpath:logback/logback.xml

image:
  path: src/main/resources/images/.
  requirements:
    standard-type: image/jpeg, image/jpg, image/png, image/bpm
    max-file-size: 5242880