spring:

  datasource:
    url: jdbc:mysql://localhost:32768/beerProjectDevelop?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ENC(GTi3pzwzixdVRCrMvXttLg==)
    password: ENC(1XPGZzYSBKjVcBFUkLw3jw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/master.xml

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


#  cache:
#    jcache:
#      config: classpath:ehcache.xml


server:
  port: 8085

logging:
  config: classpath:logback/logback.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator




