spring:
  datasource:
    url: jdbc:mysql://localhost:32768/beerProjectProduction?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: ENC(BJfoeo1WOD1X841LiYcXdw==)
    password: ENC(KEjP4V7pO9UnASeicKKjVQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/master.xml

  h2:
    console:
      enabled: false

server:
  port: 8087

logging:
  config: classpath:logback/logback.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
