spring:
  config:
    import: file:credentials/credentials-development.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:61047/beerProjectDevelop?serverTimezone=UTC&createDatabaseIfNotExist=true
    # username and password is getting from credentials directory from credential-develop.yml
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



  liquibase:
    change-log: classpath:db/master.xml



  h2:
    console:
      enabled: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

server:
  port: 8085

logging:
  config: classpath:logback/logback.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

