spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    # username and password are taken from .env file during docker-compose up
    # reuse .env.template: Fulfill data with yours values and remove suffix 'template'
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/container.xml

  h2:
    console:
      enabled: false

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000



server:
  port: 8081

logging:
  config: classpath:logback/logback.xml